#pragma once
#define EE_HANDS
#define VIAL_KEYBOARD_UID {0xdc, 0x24, 0xa0, 0x21, 0x7f, 0xe5, 0x4d, 0x2d}
#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
